### ISSUE TITLE
Code is not properly handling mismatched state config

### ISSUE THREAD

**Issue by gregswift** [rackerlabs/plight#51]
If you rename a config section, like offline, to something else but forget to update the ```[priorities]``` section, it will throw an exception without logging the error.

https://github.com/rackerlabs/plight/blob/master/plight/config.py#L99-L104

**Comment by teriyakichild** [comment]
Traceback (most recent call last):
  File "/bin/plight", line 9, in <module>
    load_entry_point('plight==0.1.2', 'console_scripts', 'plight')()
  File "/home/tony4715/plight/plight/util.py", line 99, in run
    config = plconfig.get_config()
  File "/home/tony4715/plight/plight/config.py", line 57, in get_config
    config['states'] = process_states_from_config(parser, applogger)
  File "/home/tony4715/plight/plight/config.py", line 111, in process_states_from_config
    states[state][option] = parser.get(state, option)
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'offline'

**Comment by gregswift** [comment]
Duplicate of #44
