### ISSUE TITLE
cherrypy in el5 missing process plugins

### ISSUE THREAD

**Issue by gregswift** [rackerlabs/plight#7]
[root@centos5-test plight]# plight start
  Traceback (most recent call last):
    File "/usr/bin/plight", line 7, in ?
      sys.exit(
    File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 236, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 2097, in load_entry_point
      return ep.load()
    File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 1830, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    File "build/bdist.linux-x86_64/egg/plight/util.py", line 4, in ?
  ImportError: No module named process.plugins

**Comment by rackergs** [comment]
https://github.com/rackerlabs/plight/issues/6
